### ISSUE TITLE
[FEAT] Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/TechCreators#12]
It becomes easy for beginners to make contributions on this repository if we have a CONTRIBUTING.md file. 

It should contain the steps to make contribution on this project, and also some code standards and guidelines. 

You can take inspiration from [Cardit's CONTRIBUTING.md](https://github.com/pushkaraj2007/Cardit/blob/main/contribution.md)

**Comment by geovane-gc** [comment]
Hello there! I created a PR about this issue. Feel free to send me feedbacks :)

**Comment by pushkaraj2007** [comment]
This issue has been resolved in #15
