### ISSUE TITLE
[FEAT] Add default avatar for missing or not found picture

### ISSUE THREAD

**Issue by Lourvens** [pushkaraj2007/TechCreators#38]
there's pictures that doesn't show on the website properly I think we should add default icon for user

**Comment by pushkaraj2007** [comment]
Do you want to work on this feature?

If anyone else wants to work, it is also acceptable.

**Comment by Shoetan** [comment]
Hello pushkrajal. If this issue is still open and a needed feature I will love to have a go at it.

**Comment by pushkaraj2007** [comment]
@Shoetan 

Absolutely, this issue is still open for contribution, you can work on this issue.

I'm assigning this issue to you, have a great contributing experience. 

If you have any doubts, feel free to ask.
