### ISSUE TITLE
Add 'Profile not found' message when search result is empty

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/TechCreators#65]
Currently, when a user searches for a profile that doesn't exist, there is no indication that the profile was not found. This can be confusing and frustrating for users. It would be helpful to add a message that says "Profile Not Found" when a search returns no results.

### Steps to reproduce:

1. Open the application and navigate to the search bar
2. Enter a search term for a profile that does not exist
3. Observe that there is no indication that the profile was not found

### Expected behavior: 

A message should appear indicating that the profile was not found.

### Actual behavior: 

No message appears when a profile is not found.

### Proposed solution: 

Add a message that says "Profile Not Found" when a search returns no results.

### Additional context: 

This feature would improve the user experience and make it clear when a search result is not available.

**Comment by Siddhesh-Agarwal** [comment]
Is this issue still open? Can I go ahead with it?

**Comment by pushkaraj2007** [comment]
> Is this issue still open? Can I go ahead with it?

Sure, @Siddhesh-Agarwal go ahead. 

Best of luck to you! 🚀
