### ISSUE TITLE
An overflow on the mobile preview

### ISSUE THREAD

**Issue by Akanni5** [pushkaraj2007/TechCreators#67]
Hi,
There’s an overflow on the mobile site. It caused by the navigation region, due to a wider search bar.

**Comment by pushkaraj2007** [comment]
Thanks for reporting this issue, do you want to work on this?

**Comment by Akanni5** [comment]
> Thanks for reporting this issue, do you want to work on this?

Yes!

**Comment by pushkaraj2007** [comment]
This issue has been resolved in #70
