### ISSUE TITLE
Not preview anything

### ISSUE THREAD

**Issue by kumarankit999** [pushkaraj2007/TechCreators#73]
The Website is not showing anything yet after getting started

**Comment by pushkaraj2007** [comment]
Can you please explain the issue in more detail?

**Comment by nitin-pandita** [comment]
> Can you please explain the issue in more detail?

No preview is being loaded

**Comment by kumarankit999** [comment]
There isn't showing anything, on opening the websites, it seems to white

**Comment by pushkaraj2007** [comment]
@kumarankit999 & @nitin-pandita

There is an issue in the JSON file, you can see the last profile object has not included an opening '{'.

Do you want to work on this?

**Comment by pushkaraj2007** [comment]
This issue has been resolved
