### ISSUE TITLE
Add dark mode to the website

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/TechCreators#78]
Currently, we only have a light mode on the website, it'll be great to add a dark mode on the website which will be convenient for users to choose between dark mode and light mode.

Add sun and moon icons that will change according to the mode the website is on.

Similar to how we did on [Rockout](https://rockout.vercel.app).

This issue is open for everyone to contribute.

**Comment by ynzulak** [comment]
Hello? Can i work on this ?

**Comment by pushkaraj2007** [comment]
@ynzulak 

Sure, go ahead.

Best of luck to you!

**Comment by ynzulak** [comment]
@pushkaraj2007 i will start in the morning. Can't wait to do this issue 😁

**Comment by Akash1965** [comment]
Hi @ynzulak can I work on this??
