### ISSUE TITLE
Enhancement Request: Change Scrollbar Color

### ISSUE THREAD

**Issue by Saurav-Pant** [pushkaraj2007/TechCreators#85]
I believe changing the scrollbar color would be a valuable addition to the project. The current scrollbar color does not match the overall design. I propose updating it to a more suitable color that works well with both light and dark themes, such as a neutral gray shade (#A0A0A0). 
Please assign this issue to me for implementation @pushkaraj2007

**Comment by pushkaraj2007** [comment]
@Saurav-Pant - Thanks for raising the issue!

I have assigned this issue to you.
